
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author siva
 */
public class server extends javax.swing.JFrame {

    /**
     * Creates new form server
     */
    public server() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("share details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 40, 90, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 300, 96);

        jButton1.setText("share bought");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 210, 110, 30);

        jButton2.setText("share sold");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 210, 130, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("edge details");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 40, 110, 20);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(360, 70, 210, 96);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 630, 300);

        setSize(new java.awt.Dimension(649, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        baught();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        sold();
    }//GEN-LAST:event_jButton2ActionPerformed

      public void baught()
    
    {
try
{
           String JDBC_DRIVER = "com.mysql.jdbc.Driver"; 
           Class.forName("com.mysql.jdbc.Driver");
           String DB_URL = "jdbc:mysql://localhost:3306/soft_smart_home?autoReconnect=true";
           Connection conn = DriverManager.getConnection(DB_URL,"root","system");
           
          Statement smnt = conn.createStatement();
            ResultSet rs = smnt.executeQuery("select * from share");
            while (rs.next())
            {
                
              String r1=rs.getString(1);
              String r2=rs.getString(2);
              String r3=rs.getString(3);
               if(!(r3.equals("0")))
              jTextArea1.append("user name=>"+r1+"\tshare=>"+r2+"\tbaught=>"+r3+"\n");
            }
    
}
catch(Exception ex)
{
System.out.println(ex);
}
}
      
      
      
      
  /////////////////////////////////////////////////////////
      
      
      
        public void sold()
    
    {
try
{
           String JDBC_DRIVER = "com.mysql.jdbc.Driver"; 
           Class.forName("com.mysql.jdbc.Driver");
           String DB_URL = "jdbc:mysql://localhost:3306/soft_smart_home?autoReconnect=true";
           Connection conn = DriverManager.getConnection(DB_URL,"root","system");
           
          Statement smnt = conn.createStatement();
            ResultSet rs = smnt.executeQuery("select * from share");
            while (rs.next())
            {
                
              String r1=rs.getString(1);
              String r2=rs.getString(2);
              String r3=rs.getString(4);
              if(!(r3.equals("0")))
              jTextArea1.append("user name=>"+r1+"\tshare=>"+r2+"\tsold=>"+r3+"\n");
            }
    
}
catch(Exception ex)
{
System.out.println(ex);
}
}
    
        
        
        
        
          ServerSocket ss;
   Socket s;
    public void sstart()
    {
       
     
         try{
       
             
             
             
             
      ss =new ServerSocket(6001);
        String data;
         System.out.println("listening");
         
         while(true)
         {
              s=ss.accept();

         // jTextArea1.append(s.toString());
         
	ObjectInputStream inn=new ObjectInputStream(s.getInputStream());
   Vector   b=(Vector)inn.readObject();
      System.out.println("the received values is"+b);
     String bb=b.get(0).toString();
   
     
     
      jTextArea2.append("\n messagw recieved=>"+bb);
         
         
     if(bb.equals("b"))
     {
           jTextArea2.append("\n attack detected but it crashes tower2");
     }
         
     ObjectOutputStream dis=new ObjectOutputStream(s.getOutputStream());
     dis.writeObject("ack");
   
         }
        }
        catch(Exception e)
        {
           System.out.println(e); 
        }
    }
   
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
        
        
         server bb=new server();
           bb.setVisible(true);
        bb.sstart();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
